# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui_roboControl.ui'
#
# Created: Wed Nov 19 21:45:24 2014
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.setEnabled(True)
        MainWindow.resize(594, 534)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Camera-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 551, 465))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(self.horizontalLayoutWidget)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.webView = QtWebKit.QWebView(self.frame)
        self.webView.setGeometry(QtCore.QRect(0, 0, 261, 221))
        self.webView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.webView.setObjectName(_fromUtf8("webView"))
        self.horizontalLayout.addWidget(self.frame)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_3 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_2.addWidget(self.label_3)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.pushButtonRx = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonRx.setObjectName(_fromUtf8("pushButtonRx"))
        self.horizontalLayout_9.addWidget(self.pushButtonRx)
        self.pushButtonTx = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButtonTx.setObjectName(_fromUtf8("pushButtonTx"))
        self.horizontalLayout_9.addWidget(self.pushButtonTx)
        self.verticalLayout_2.addLayout(self.horizontalLayout_9)
        self.pushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.verticalLayout_2.addWidget(self.pushButton)
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(64, 64))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Camera-icon2.png")))
        self.label.setScaledContents(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.radioCamera = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioCamera.setText(_fromUtf8(""))
        self.radioCamera.setObjectName(_fromUtf8("radioCamera"))
        self.horizontalLayout_5.addWidget(self.radioCamera)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_2 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_2.setEnabled(True)
        self.label_2.setMaximumSize(QtCore.QSize(64, 64))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Misc-Tip-icon.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_2.addWidget(self.label_2)
        self.radioCamLight = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioCamLight.setText(_fromUtf8(""))
        self.radioCamLight.setObjectName(_fromUtf8("radioCamLight"))
        self.horizontalLayout_2.addWidget(self.radioCamLight)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_6 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_3.addWidget(self.label_6)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_4 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_8.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.horizontalLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_8.addWidget(self.label_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.progressLeftMotor = QtGui.QProgressBar(self.horizontalLayoutWidget)
        self.progressLeftMotor.setProperty("value", 24)
        self.progressLeftMotor.setOrientation(QtCore.Qt.Vertical)
        self.progressLeftMotor.setObjectName(_fromUtf8("progressLeftMotor"))
        self.horizontalLayout_7.addWidget(self.progressLeftMotor)
        self.progressRightMotor = QtGui.QProgressBar(self.horizontalLayoutWidget)
        self.progressRightMotor.setProperty("value", 24)
        self.progressRightMotor.setOrientation(QtCore.Qt.Vertical)
        self.progressRightMotor.setObjectName(_fromUtf8("progressRightMotor"))
        self.horizontalLayout_7.addWidget(self.progressRightMotor)
        self.verticalLayout_3.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_6.addLayout(self.verticalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pushLeft = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushLeft.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Left-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushLeft.setIcon(icon1)
        self.pushLeft.setIconSize(QtCore.QSize(32, 32))
        self.pushLeft.setObjectName(_fromUtf8("pushLeft"))
        self.gridLayout.addWidget(self.pushLeft, 2, 0, 1, 1)
        self.pushDown = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushDown.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Down-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushDown.setIcon(icon2)
        self.pushDown.setIconSize(QtCore.QSize(32, 32))
        self.pushDown.setObjectName(_fromUtf8("pushDown"))
        self.gridLayout.addWidget(self.pushDown, 3, 1, 1, 1)
        self.pushUp = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushUp.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Up-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushUp.setIcon(icon3)
        self.pushUp.setIconSize(QtCore.QSize(32, 32))
        self.pushUp.setObjectName(_fromUtf8("pushUp"))
        self.gridLayout.addWidget(self.pushUp, 1, 1, 1, 1)
        self.pushRight = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushRight.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Right-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushRight.setIcon(icon4)
        self.pushRight.setIconSize(QtCore.QSize(32, 32))
        self.pushRight.setObjectName(_fromUtf8("pushRight"))
        self.gridLayout.addWidget(self.pushRight, 2, 3, 1, 1)
        self.pushDownRight = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushDownRight.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Down-Right-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushDownRight.setIcon(icon5)
        self.pushDownRight.setIconSize(QtCore.QSize(32, 32))
        self.pushDownRight.setObjectName(_fromUtf8("pushDownRight"))
        self.gridLayout.addWidget(self.pushDownRight, 3, 3, 1, 1)
        self.pushUpRight = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushUpRight.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Up-Right-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushUpRight.setIcon(icon6)
        self.pushUpRight.setIconSize(QtCore.QSize(32, 32))
        self.pushUpRight.setObjectName(_fromUtf8("pushUpRight"))
        self.gridLayout.addWidget(self.pushUpRight, 1, 3, 1, 1)
        self.pushUpLeft = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushUpLeft.setText(_fromUtf8(""))
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Up-Left-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushUpLeft.setIcon(icon7)
        self.pushUpLeft.setIconSize(QtCore.QSize(32, 32))
        self.pushUpLeft.setObjectName(_fromUtf8("pushUpLeft"))
        self.gridLayout.addWidget(self.pushUpLeft, 1, 0, 1, 1)
        self.pushDownLeft = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushDownLeft.setText(_fromUtf8(""))
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Arrows-Down-Left-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushDownLeft.setIcon(icon8)
        self.pushDownLeft.setIconSize(QtCore.QSize(32, 32))
        self.pushDownLeft.setObjectName(_fromUtf8("pushDownLeft"))
        self.gridLayout.addWidget(self.pushDownLeft, 3, 0, 1, 1)
        self.pushStop = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pushStop.setText(_fromUtf8(""))
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8("../../../../Pictures/QTResources/Stop-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushStop.setIcon(icon9)
        self.pushStop.setIconSize(QtCore.QSize(32, 32))
        self.pushStop.setObjectName(_fromUtf8("pushStop"))
        self.gridLayout.addWidget(self.pushStop, 2, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 594, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "RoboControl", None))
        self.label_3.setText(_translate("MainWindow", "Robolink", None))
        self.pushButtonRx.setText(_translate("MainWindow", "Rx", None))
        self.pushButtonTx.setText(_translate("MainWindow", "Tx", None))
        self.pushButton.setText(_translate("MainWindow", "Reset", None))
        self.label_6.setText(_translate("MainWindow", "Motorpower", None))
        self.label_4.setText(_translate("MainWindow", "Left", None))
        self.label_5.setText(_translate("MainWindow", "Right", None))

from PyQt4 import QtWebKit
